/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *Jacob L
 * Oct 15, 2018
 * Creates and runs a multiple choice quiz
 */
public class MultiQuiz extends javax.swing.JFrame {

    //Global Variables
    String questionDisplay = "One";
    int questionCorrect = 0;
    int questionIncorrect = 0;
    double percentageCorrect = 0;
    
    // Setup Questions
    String quOneText = "What is the name of this flag? ~ A)Pearson Pendant B)La Tricoleur C)The Triple Leaf D)Drapeau du Cote"; //#1 + ANS = A
    String quTwoText = "What is the name of this flag? ~ A)Flaag Deutche B)Prinservlag C)Des Nederlandes D)Lorangistes"; //#2 + ANS = B
    String quThreeText = "This flag is from what Nation? ~ A)USA B)United Netherlands C)Liberia D)Libya"; //#3 + ANS = C
    String quFourText = "This flag is from what Nation? ~ A)Uruguay B)Paraguay C)California D)Argentina"; //#4 + ANS = D
    String quFiveText = "How many American fags were planted on the moon? ~ A)6 B)10 C)12 d)4"; //#5 + ANS = A
    
    public MultiQuiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questionAreaScrollPane = new javax.swing.JScrollPane();
        questionOutputTextArea = new javax.swing.JTextArea();
        confirmButtonFive = new javax.swing.JButton();
        confirmButtonDone = new javax.swing.JButton();
        flagDisplayLabelQuOne = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        sideBackgroundPanel = new javax.swing.JPanel();
        questionsCorrectLabel = new javax.swing.JLabel();
        questionsIncorrectLabel = new javax.swing.JLabel();
        percentageCorrectLabel = new javax.swing.JLabel();
        questionsCorrectOutputLabel = new javax.swing.JLabel();
        questionsIncorrectOutputLabel = new javax.swing.JLabel();
        percentageCorrectOutputLabel = new javax.swing.JLabel();
        inputAnswerField = new javax.swing.JTextField();
        feedbackLabel = new javax.swing.JLabel();
        confirmButtonOne = new javax.swing.JButton();
        test = new javax.swing.JLabel();
        confirmButtonTwo = new javax.swing.JButton();
        confirmButtonThree = new javax.swing.JButton();
        confirmButtonFour = new javax.swing.JButton();
        flagDisplayLabelQuThree = new javax.swing.JLabel();
        flagDisplayLabelQuTwo = new javax.swing.JLabel();
        flagDisplayLabelQuFour = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        questionOutputTextArea.setEditable(false);
        questionOutputTextArea.setColumns(20);
        questionOutputTextArea.setLineWrap(true);
        questionOutputTextArea.setRows(2);
        questionAreaScrollPane.setViewportView(questionOutputTextArea);

        confirmButtonFive.setText("CONFIRM 5");
        confirmButtonFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonFiveActionPerformed(evt);
            }
        });

        confirmButtonDone.setText("DONE");
        confirmButtonDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonDoneActionPerformed(evt);
            }
        });

        flagDisplayLabelQuOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Canada_Pearson_Pennant_1964.png"))); // NOI18N

        titleLabel.setFont(new java.awt.Font("Superheterodyne", 0, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 102, 0));
        titleLabel.setText("Expert Flag Quiz");

        startButton.setFont(new java.awt.Font("TI Uni", 1, 11)); // NOI18N
        startButton.setText("START");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        sideBackgroundPanel.setBackground(new java.awt.Color(204, 255, 204));
        sideBackgroundPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        questionsCorrectLabel.setText("Questions Correct:");

        questionsIncorrectLabel.setText("Questions Incorrect:");

        percentageCorrectLabel.setText("Percentage Correct:");

        questionsCorrectOutputLabel.setText("~");

        questionsIncorrectOutputLabel.setText("~");

        percentageCorrectOutputLabel.setText("~");

        javax.swing.GroupLayout sideBackgroundPanelLayout = new javax.swing.GroupLayout(sideBackgroundPanel);
        sideBackgroundPanel.setLayout(sideBackgroundPanelLayout);
        sideBackgroundPanelLayout.setHorizontalGroup(
            sideBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBackgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(questionsCorrectLabel)
                    .addComponent(questionsIncorrectLabel)
                    .addComponent(percentageCorrectLabel)
                    .addComponent(questionsIncorrectOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionsCorrectOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentageCorrectOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        sideBackgroundPanelLayout.setVerticalGroup(
            sideBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBackgroundPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(questionsCorrectLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(questionsCorrectOutputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(questionsIncorrectLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(questionsIncorrectOutputLabel)
                .addGap(64, 64, 64)
                .addComponent(percentageCorrectLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(percentageCorrectOutputLabel)
                .addGap(51, 51, 51))
        );

        inputAnswerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAnswerFieldActionPerformed(evt);
            }
        });

        feedbackLabel.setText("~");

        confirmButtonOne.setText("CONFIRM 1");
        confirmButtonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonOneActionPerformed(evt);
            }
        });

        confirmButtonTwo.setText("CONFIRM 2");
        confirmButtonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonTwoActionPerformed(evt);
            }
        });

        confirmButtonThree.setText("CONFIRM 3");
        confirmButtonThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonThreeActionPerformed(evt);
            }
        });

        confirmButtonFour.setText("CONFIRM 4");
        confirmButtonFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonFourActionPerformed(evt);
            }
        });

        flagDisplayLabelQuThree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2000px-Flag_of_Liberia.svg.png"))); // NOI18N

        flagDisplayLabelQuTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1200px-Prinsenvlag.svg.png"))); // NOI18N

        flagDisplayLabelQuFour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1200px-Flag_of_Argentina.svg.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(confirmButtonFour)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(confirmButtonFive)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(confirmButtonDone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(confirmButtonOne)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(confirmButtonTwo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(confirmButtonThree))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(startButton))
                                    .addComponent(feedbackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(test, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(inputAnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(questionAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(flagDisplayLabelQuOne, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(flagDisplayLabelQuTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(flagDisplayLabelQuThree, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(3, 3, 3)))
                                    .addComponent(flagDisplayLabelQuFour, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addComponent(sideBackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(flagDisplayLabelQuTwo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(flagDisplayLabelQuOne, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(test, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(flagDisplayLabelQuThree, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(flagDisplayLabelQuFour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(questionAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputAnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(feedbackLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmButtonThree)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(confirmButtonOne)
                        .addComponent(confirmButtonTwo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButtonFour)
                    .addComponent(confirmButtonFive)
                    .addComponent(confirmButtonDone))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonFiveActionPerformed
        // Get Answers
        String userAnswer = (inputAnswerField.getText());

        //Compare and Check if its Right
        if (questionDisplay.equals("Five") && userAnswer.equals("A") || userAnswer.equals("a")){
            questionCorrect = questionCorrect + 1;
            questionsCorrectOutputLabel.setText(""+questionCorrect);
            inputAnswerField.setText("");
            questionDisplay = "Done";
            //test.setText(questionDisplay);
            questionOutputTextArea.setText("Click Done Please");
            
            //randomized element
            int randomPhrase;
            randomPhrase = (int)Math.round(Math.random()*2+1);
            switch (randomPhrase) {
                case 1:
                    feedbackLabel.setText("A true vexiologist in the making");
                    break;
                case 2:
                    feedbackLabel.setText("Vonderbar!");
                    break;
                case 3:
                    feedbackLabel.setText("Planted among the stars.");
                    break;
                
            }
        }
        else {
            questionIncorrect = questionIncorrect + 1;
            questionsIncorrectOutputLabel.setText(""+questionIncorrect);
            inputAnswerField.setText("");
            questionDisplay = "Done";
            //test.setText(questionDisplay);
            questionOutputTextArea.setText("Click Done Please");
            
            //randomized element
            int randomPhrase;
            randomPhrase = (int)Math.round(Math.random()*2+1);
            switch (randomPhrase) {
                case 1:
                    feedbackLabel.setText("Stay on target commander.");
                    break;
                case 2:
                    feedbackLabel.setText("Blown away in the strong winds?");
                    break;
                case 3:
                    feedbackLabel.setText("Red, green, white. How original!");
                    break;
                
            }
        }
    }//GEN-LAST:event_confirmButtonFiveActionPerformed

    private void confirmButtonDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonDoneActionPerformed
        // Percent Right
        double percCorrect = ((double)questionCorrect/5)*100;
        
        percCorrect = percCorrect * 100 ;
        percCorrect = Math.round(percCorrect) ;
        percCorrect = percCorrect / 100 ;
        
        percentageCorrectOutputLabel.setText(""+percCorrect+"%");
        
        //clear comment
        feedbackLabel.setText("");
    }//GEN-LAST:event_confirmButtonDoneActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed

        // Display Questions
        questionOutputTextArea.setText(quOneText);
        //image
        //Update Counters
        questionsCorrectOutputLabel.setText(""+questionCorrect);
        questionsIncorrectOutputLabel.setText(""+questionIncorrect);

    }//GEN-LAST:event_startButtonActionPerformed

    private void inputAnswerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAnswerFieldActionPerformed
         //redacted
    }//GEN-LAST:event_inputAnswerFieldActionPerformed

    private void confirmButtonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonOneActionPerformed
        // Get Answers
        String userAnswer = (inputAnswerField.getText());

        if (questionDisplay.equals("One") && userAnswer.equals("A") || userAnswer.equals("a")){
            questionCorrect = questionCorrect + 1;
            questionsCorrectOutputLabel.setText(""+questionCorrect);
            inputAnswerField.setText("");
            questionDisplay = "Two";
            //test.setText(questionDisplay);
            questionOutputTextArea.setText(quTwoText);
            
            //randomized element
            int randomPhrase;
            randomPhrase = (int)Math.round(Math.random()*2+1);
            switch (randomPhrase) {
                case 1:
                    feedbackLabel.setText("A true vexiologist in the making");
                    break;
                case 2:
                    feedbackLabel.setText("Vonderbar!");
                    break;
                case 3:
                    feedbackLabel.setText("Planted among the stars.");
                    break;
                
            }
                
    
        }
        else {
            questionIncorrect = questionIncorrect + 1;
            questionsIncorrectOutputLabel.setText(""+questionIncorrect);
            inputAnswerField.setText("");
            questionDisplay = "Two";
            //test.setText(questionDisplay);
            questionOutputTextArea.setText(quTwoText);
            
            //randomized element
            int randomPhrase;
            randomPhrase = (int)Math.round(Math.random()*2+1);
            switch (randomPhrase) {
                case 1:
                    feedbackLabel.setText("Stay on target commander.");
                    break;
                case 2:
                    feedbackLabel.setText("Blown away in the strong winds?");
                    break;
                case 3:
                    feedbackLabel.setText("Red, green, white. How original!");
                    break;
                
            }
        }

    }//GEN-LAST:event_confirmButtonOneActionPerformed

    private void confirmButtonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonTwoActionPerformed
        // Get Answers
        String userAnswer = (inputAnswerField.getText());

        if (userAnswer.equals("B") || userAnswer.equals("b")){
            questionCorrect = questionCorrect + 1;
            questionsCorrectOutputLabel.setText(""+questionCorrect);
            inputAnswerField.setText("");
            questionDisplay = "Three";
            //test.setText(questionDisplay);
            questionOutputTextArea.setText(quThreeText);
            
            //randomized element
            int randomPhrase;
            randomPhrase = (int)Math.round(Math.random()*2+1);
            switch (randomPhrase) {
                case 1:
                    feedbackLabel.setText("A true vexiologist in the making");
                    break;
                case 2:
                    feedbackLabel.setText("Vonderbar!");
                    break;
                case 3:
                    feedbackLabel.setText("Planted among the stars.");
                    break;
                
            }
        }
        else {
            questionIncorrect = questionIncorrect + 1;
            questionsIncorrectOutputLabel.setText(""+questionIncorrect);
            inputAnswerField.setText("");
            questionDisplay = "Three";
            //test.setText(questionDisplay);
            questionOutputTextArea.setText(quThreeText);
            
            //randomized element
            int randomPhrase;
            randomPhrase = (int)Math.round(Math.random()*2+1);
            switch (randomPhrase) {
                case 1:
                    feedbackLabel.setText("Stay on target commander.");
                    break;
                case 2:
                    feedbackLabel.setText("Blown away in the strong winds?");
                    break;
                case 3:
                    feedbackLabel.setText("Red, green, white. How original!");
                    break;
                
            }
        }

    }//GEN-LAST:event_confirmButtonTwoActionPerformed

    private void confirmButtonThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonThreeActionPerformed
        // Get Answers
        String userAnswer = (inputAnswerField.getText());

        if (userAnswer.equals("C") || userAnswer.equals("c")){
            questionCorrect = questionCorrect + 1;
            questionsCorrectOutputLabel.setText(""+questionCorrect);
            inputAnswerField.setText("");
            questionDisplay = "Four";
            //test.setText(questionDisplay);
            questionOutputTextArea.setText(quFourText);
            
            //randomized element
            int randomPhrase;
            randomPhrase = (int)Math.round(Math.random()*2+1);
            switch (randomPhrase) {
                case 1:
                    feedbackLabel.setText("A true vexiologist in the making");
                    break;
                case 2:
                    feedbackLabel.setText("Vonderbar!");
                    break;
                case 3:
                    feedbackLabel.setText("Planted among the stars.");
                    break;
                
            }
        }
        else {
            questionIncorrect = questionIncorrect + 1;
            questionsIncorrectOutputLabel.setText(""+questionIncorrect);
            inputAnswerField.setText("");
            questionDisplay = "Four";
            //test.setText(questionDisplay);
            questionOutputTextArea.setText(quFourText);
            
            //randomized element
            int randomPhrase;
            randomPhrase = (int)Math.round(Math.random()*2+1);
            switch (randomPhrase) {
                case 1:
                    feedbackLabel.setText("Stay on target commander.");
                    break;
                case 2:
                    feedbackLabel.setText("Blown away in the strong winds?");
                    break;
                case 3:
                    feedbackLabel.setText("Red, green, white. How original!");
                    break;
                
            }
        }
    }//GEN-LAST:event_confirmButtonThreeActionPerformed

    private void confirmButtonFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonFourActionPerformed
        // Get Answers
        String userAnswer = (inputAnswerField.getText());

        if (questionDisplay.equals("Four") && userAnswer.equals("D") || userAnswer.equals("d")){
            questionCorrect = questionCorrect + 1;
            questionsCorrectOutputLabel.setText(""+questionCorrect);
            inputAnswerField.setText("");
            questionDisplay = "Five";
            //test.setText(questionDisplay);
            questionOutputTextArea.setText(quFiveText);
            
            //randomized element
            int randomPhrase;
            randomPhrase = (int)Math.round(Math.random()*2+1);
            switch (randomPhrase) {
                case 1:
                    feedbackLabel.setText("A true vexiologist in the making");
                    break;
                case 2:
                    feedbackLabel.setText("Vonderbar!");
                    break;
                case 3:
                    feedbackLabel.setText("Planted among the stars.");
                    break;
                
            }
        }
        else {
            questionIncorrect = questionIncorrect + 1;
            questionsIncorrectOutputLabel.setText(""+questionIncorrect);
            inputAnswerField.setText("");
            questionDisplay = "Five";
            //test.setText(questionDisplay);
            questionOutputTextArea.setText(quFiveText);
            
            //randomized element
            int randomPhrase;
            randomPhrase = (int)Math.round(Math.random()*2+1);
            switch (randomPhrase) {
                case 1:
                    feedbackLabel.setText("Stay on target commander.");
                    break;
                case 2:
                    feedbackLabel.setText("Blown away in the strong winds?");
                    break;
                case 3:
                    feedbackLabel.setText("Red, green, white. How original!");
                    break;
                
            }
        }
    }//GEN-LAST:event_confirmButtonFourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmButtonDone;
    private javax.swing.JButton confirmButtonFive;
    private javax.swing.JButton confirmButtonFour;
    private javax.swing.JButton confirmButtonOne;
    private javax.swing.JButton confirmButtonThree;
    private javax.swing.JButton confirmButtonTwo;
    private javax.swing.JLabel feedbackLabel;
    private javax.swing.JLabel flagDisplayLabelQuFour;
    private javax.swing.JLabel flagDisplayLabelQuOne;
    private javax.swing.JLabel flagDisplayLabelQuThree;
    private javax.swing.JLabel flagDisplayLabelQuTwo;
    private javax.swing.JTextField inputAnswerField;
    private javax.swing.JLabel percentageCorrectLabel;
    private javax.swing.JLabel percentageCorrectOutputLabel;
    private javax.swing.JScrollPane questionAreaScrollPane;
    private javax.swing.JTextArea questionOutputTextArea;
    private javax.swing.JLabel questionsCorrectLabel;
    private javax.swing.JLabel questionsCorrectOutputLabel;
    private javax.swing.JLabel questionsIncorrectLabel;
    private javax.swing.JLabel questionsIncorrectOutputLabel;
    private javax.swing.JPanel sideBackgroundPanel;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel test;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
